name: ART Gradle Tag
on:
  push:
    tags:
      - '*'
jobs:
  gradle-publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 1.8 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean publish --max-workers 8 --parallel -Ppublisher.username=${publisherUsername} -Ppublisher.password=${publisherPassword} -Pversion=${version}
        env:
          publisherUsername: ${{ secrets.PUBLISHER_USERNAME }}
          publisherPassword: ${{ secrets.PUBLISHER_PASSWORD }}
          version: ${{ env.TAG }}
