name: ART Gradle Branch
on:
  push:
    branches-ignore:
      - main
jobs:
  gradle-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ 1.8, 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build --max-workers 8 --parallel
